[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ulibarpam"
version = "0.1.0"
dependencies = [
  "numpy",
  "scipy",
  "opencv-python",
  "click",
]

[project.scripts]
arpam-recon = "ulibarpam.main_cli:main"
